"""create audit and scenario snapshot tables

Revision ID: 0001
Revises: 
Create Date: 2026-07-29 17:21:42.714524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.poli_insight.infrastructure.database.types import UUIDString, UTCDateTime

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('audit_event_id', UUIDString(length=36), nullable=False),
    sa.Column('session_id', UUIDString(length=36), nullable=True),
    sa.Column('occurred_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.String(length=100), nullable=True),
    sa.Column('actor_display_snapshot', sa.String(length=200), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('reason_code', sa.String(length=100), nullable=True),
    sa.Column('reason_text', sa.Text(), nullable=True),
    sa.Column('before_json', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('after_json', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('patch_json', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.Column('causation_event_id', UUIDString(length=36), nullable=True),
    sa.Column('source_metadata_json', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('previous_event_hash', sa.String(length=64), nullable=True),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.Integer(), server_default='1', nullable=False),
    sa.CheckConstraint("action IN ('created', 'updated', 'opened', 'closed', 'invited', 'redeemed', 'submitted', 'validated', 'included', 'excluded', 'processed', 'analyzed', 'approved', 'published', 'withdrawn', 'redacted')", name='ck_audit_events_action_allowed'),
    sa.CheckConstraint("actor_type IN ('user', 'participant', 'system', 'ai_service', 'import_process', 'api_client')", name='ck_audit_events_actor_type_allowed'),
    sa.CheckConstraint('length(event_hash) = 64', name='ck_audit_events_event_hash_length'),
    sa.CheckConstraint('length(trim(correlation_id)) > 0', name='ck_audit_events_correlation_id_nonempty'),
    sa.CheckConstraint('length(trim(entity_id)) > 0', name='ck_audit_events_entity_id_nonempty'),
    sa.CheckConstraint('length(trim(entity_type)) > 0', name='ck_audit_events_entity_type_nonempty'),
    sa.CheckConstraint('previous_event_hash IS NULL OR length(previous_event_hash) = 64', name='ck_audit_events_previous_hash_length'),
    sa.CheckConstraint('schema_version >= 1', name='ck_audit_events_schema_version_positive'),
    sa.ForeignKeyConstraint(['causation_event_id'], ['audit_events.audit_event_id'], name='fk_audit_events_causation_event_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('audit_event_id', name=op.f('pk_audit_events'))
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_events_action_occurred', ['action', 'occurred_at'], unique=False)
        batch_op.create_index('ix_audit_events_causation_event_id', ['causation_event_id'], unique=False)
        batch_op.create_index('ix_audit_events_correlation_id', ['correlation_id'], unique=False)
        batch_op.create_index('ix_audit_events_entity', ['entity_type', 'entity_id', 'occurred_at'], unique=False)
        batch_op.create_index('ix_audit_events_session_occurred', ['session_id', 'occurred_at'], unique=False)

    op.create_table('scenario_definitions',
    sa.Column('scenario_definition_id', UUIDString(length=36), nullable=False),
    sa.Column('scenario_key', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False),
    sa.CheckConstraint("status IN ('active', 'retired')", name='ck_scenario_definitions_status_allowed'),
    sa.PrimaryKeyConstraint('scenario_definition_id', name=op.f('pk_scenario_definitions')),
    sa.UniqueConstraint('scenario_key', name='uq_scenario_definitions_scenario_key')
    )
    with op.batch_alter_table('scenario_definitions', schema=None) as batch_op:
        batch_op.create_index('ix_scenario_definitions_domain', ['domain'], unique=False)
        batch_op.create_index('ix_scenario_definitions_status', ['status'], unique=False)

    op.create_table('scenario_snapshots',
    sa.Column('scenario_snapshot_id', UUIDString(length=36), nullable=False),
    sa.Column('scenario_definition_id', UUIDString(length=36), nullable=False),
    sa.Column('declared_version', sa.String(length=50), nullable=False),
    sa.Column('scenario_type', sa.String(length=50), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('policy_question', sa.Text(), nullable=False),
    sa.Column('manifest_json', sa.JSON(none_as_null=True), nullable=False),
    sa.Column('manifest_schema_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('root_hash', sa.String(length=64), nullable=False),
    sa.Column('materialized_input_hash', sa.String(length=64), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=True),
    sa.Column('importer_version', sa.String(length=100), nullable=False),
    sa.Column('import_environment_json', sa.JSON(none_as_null=True), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('ready_at', UTCDateTime(timezone=True), nullable=True),
    sa.CheckConstraint("scenario_type IN ('standard', 'hierarchical')", name='ck_scenario_snapshots_scenario_type_allowed'),
    sa.CheckConstraint("status <> 'ready' OR ready_at IS NOT NULL", name='ck_scenario_snapshots_ready_has_timestamp'),
    sa.CheckConstraint("status IN ('validating', 'ready', 'invalid', 'retired')", name='ck_scenario_snapshots_status_allowed'),
    sa.CheckConstraint('length(materialized_input_hash) = 64', name='ck_scenario_snapshots_materialized_hash_length'),
    sa.CheckConstraint('length(root_hash) = 64', name='ck_scenario_snapshots_root_hash_length'),
    sa.CheckConstraint('manifest_schema_version >= 1', name='ck_scenario_snapshots_manifest_schema_version_positive'),
    sa.CheckConstraint('schema_version >= 1', name='ck_scenario_snapshots_schema_version_positive'),
    sa.ForeignKeyConstraint(['scenario_definition_id'], ['scenario_definitions.scenario_definition_id'], name='fk_scenario_snapshots_definition_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('scenario_snapshot_id', name=op.f('pk_scenario_snapshots')),
    sa.UniqueConstraint('root_hash', name='uq_scenario_snapshots_root_hash')
    )
    with op.batch_alter_table('scenario_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_scenario_snapshots_definition_created', ['scenario_definition_id', 'created_at'], unique=False)
        batch_op.create_index('ix_scenario_snapshots_status', ['status'], unique=False)

    op.create_table('scenario_alternatives',
    sa.Column('alternative_id', UUIDString(length=36), nullable=False),
    sa.Column('scenario_snapshot_id', UUIDString(length=36), nullable=False),
    sa.Column('alternative_key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(none_as_null=True), nullable=False),
    sa.CheckConstraint('display_order >= 0', name='ck_scenario_alternatives_display_order_nonnegative'),
    sa.ForeignKeyConstraint(['scenario_snapshot_id'], ['scenario_snapshots.scenario_snapshot_id'], name='fk_scenario_alternatives_snapshot_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alternative_id', name=op.f('pk_scenario_alternatives')),
    sa.UniqueConstraint('scenario_snapshot_id', 'alternative_id', name='uq_scenario_alternatives_snapshot_id_alternative_id'),
    sa.UniqueConstraint('scenario_snapshot_id', 'alternative_key', name='uq_scenario_alternatives_snapshot_key')
    )
    with op.batch_alter_table('scenario_alternatives', schema=None) as batch_op:
        batch_op.create_index('ix_scenario_alternatives_snapshot_order', ['scenario_snapshot_id', 'display_order'], unique=False)

    op.create_table('scenario_criteria',
    sa.Column('criterion_id', UUIDString(length=36), nullable=False),
    sa.Column('scenario_snapshot_id', UUIDString(length=36), nullable=False),
    sa.Column('criterion_key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('direction', sa.String(length=50), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=100), nullable=True),
    sa.Column('parent_criterion_id', UUIDString(length=36), nullable=True),
    sa.Column('required', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('source_column', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(none_as_null=True), nullable=False),
    sa.CheckConstraint("data_type IN ('numeric', 'ordinal', 'categorical', 'boolean')", name='ck_scenario_criteria_data_type_allowed'),
    sa.CheckConstraint("direction IN ('cost', 'benefit')", name='ck_scenario_criteria_direction_allowed'),
    sa.CheckConstraint('display_order >= 0', name='ck_scenario_criteria_display_order_nonnegative'),
    sa.ForeignKeyConstraint(['parent_criterion_id'], ['scenario_criteria.criterion_id'], name='fk_scenario_criteria_parent_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_snapshot_id'], ['scenario_snapshots.scenario_snapshot_id'], name='fk_scenario_criteria_snapshot_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('criterion_id', name=op.f('pk_scenario_criteria')),
    sa.UniqueConstraint('scenario_snapshot_id', 'criterion_id', name='uq_scenario_criteria_snapshot_id_criterion_id'),
    sa.UniqueConstraint('scenario_snapshot_id', 'criterion_key', name='uq_scenario_criteria_snapshot_key')
    )
    with op.batch_alter_table('scenario_criteria', schema=None) as batch_op:
        batch_op.create_index('ix_scenario_criteria_parent_id', ['parent_criterion_id'], unique=False)
        batch_op.create_index('ix_scenario_criteria_snapshot_order', ['scenario_snapshot_id', 'display_order'], unique=False)

    op.create_table('scenario_scales',
    sa.Column('scale_id', UUIDString(length=36), nullable=False),
    sa.Column('scenario_snapshot_id', UUIDString(length=36), nullable=False),
    sa.Column('scale_key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('scale_type', sa.String(length=100), nullable=False),
    sa.Column('ordered', sa.Boolean(), nullable=False),
    sa.Column('definition_version', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(none_as_null=True), nullable=False),
    sa.CheckConstraint('definition_version >= 1', name='ck_scenario_scales_definition_version_positive'),
    sa.ForeignKeyConstraint(['scenario_snapshot_id'], ['scenario_snapshots.scenario_snapshot_id'], name='fk_scenario_scales_snapshot_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scale_id', name=op.f('pk_scenario_scales')),
    sa.UniqueConstraint('scenario_snapshot_id', 'scale_key', name='uq_scenario_scales_snapshot_key')
    )
    with op.batch_alter_table('scenario_scales', schema=None) as batch_op:
        batch_op.create_index('ix_scenario_scales_snapshot_id', ['scenario_snapshot_id'], unique=False)

    op.create_table('scenario_snapshot_files',
    sa.Column('snapshot_file_id', UUIDString(length=36), nullable=False),
    sa.Column('scenario_snapshot_id', UUIDString(length=36), nullable=False),
    sa.Column('logical_path', sa.String(length=500), nullable=False),
    sa.Column('file_role', sa.String(length=50), nullable=False),
    sa.Column('media_type', sa.String(length=255), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('inline_bytes', sa.LargeBinary(), nullable=True),
    sa.Column('immutable_object_uri', sa.Text(), nullable=True),
    sa.CheckConstraint("file_role IN ('scenario_config', 'criteria_config', 'data_source_config', 'preprocessing_config', 'session_rules', 'ui_config', 'source_data', 'custom_function', 'other')", name='ck_scenario_snapshot_files_role_allowed'),
    sa.CheckConstraint('(inline_bytes IS NOT NULL AND immutable_object_uri IS NULL) OR (inline_bytes IS NULL AND immutable_object_uri IS NOT NULL)', name='ck_scenario_snapshot_files_exactly_one_content_location'),
    sa.CheckConstraint('byte_size >= 0', name='ck_scenario_snapshot_files_byte_size_nonnegative'),
    sa.CheckConstraint('length(content_hash) = 64', name='ck_scenario_snapshot_files_content_hash_length'),
    sa.ForeignKeyConstraint(['scenario_snapshot_id'], ['scenario_snapshots.scenario_snapshot_id'], name='fk_scenario_snapshot_files_snapshot_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_file_id', name=op.f('pk_scenario_snapshot_files')),
    sa.UniqueConstraint('scenario_snapshot_id', 'logical_path', name='uq_scenario_snapshot_files_snapshot_path')
    )
    with op.batch_alter_table('scenario_snapshot_files', schema=None) as batch_op:
        batch_op.create_index('ix_scenario_snapshot_files_content_hash', ['content_hash'], unique=False)
        batch_op.create_index('ix_scenario_snapshot_files_snapshot_role', ['scenario_snapshot_id', 'file_role'], unique=False)

    op.create_table('scenario_matrix_values',
    sa.Column('scenario_snapshot_id', UUIDString(length=36), nullable=False),
    sa.Column('alternative_id', UUIDString(length=36), nullable=False),
    sa.Column('criterion_id', UUIDString(length=36), nullable=False),
    sa.Column('value_numeric', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('value_json', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('source_provenance_json', sa.JSON(none_as_null=True), nullable=False),
    sa.CheckConstraint('(value_numeric IS NOT NULL AND value_json IS NULL) OR (value_numeric IS NULL AND value_json IS NOT NULL)', name='ck_scenario_matrix_values_exactly_one_value'),
    sa.ForeignKeyConstraint(['scenario_snapshot_id', 'alternative_id'], ['scenario_alternatives.scenario_snapshot_id', 'scenario_alternatives.alternative_id'], name='fk_scenario_matrix_values_snapshot_alternative', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_snapshot_id', 'criterion_id'], ['scenario_criteria.scenario_snapshot_id', 'scenario_criteria.criterion_id'], name='fk_scenario_matrix_values_snapshot_criterion', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_snapshot_id'], ['scenario_snapshots.scenario_snapshot_id'], name='fk_scenario_matrix_values_snapshot_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scenario_snapshot_id', 'alternative_id', 'criterion_id', name=op.f('pk_scenario_matrix_values'))
    )
    with op.batch_alter_table('scenario_matrix_values', schema=None) as batch_op:
        batch_op.create_index('ix_scenario_matrix_values_alternative_id', ['alternative_id'], unique=False)
        batch_op.create_index('ix_scenario_matrix_values_criterion_id', ['criterion_id'], unique=False)

    op.create_table('scenario_scale_values',
    sa.Column('scale_value_id', UUIDString(length=36), nullable=False),
    sa.Column('scale_id', UUIDString(length=36), nullable=False),
    sa.Column('stable_value_key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('numeric_value', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('fuzzy_lower', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('fuzzy_middle', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('fuzzy_upper', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('metadata_json', sa.JSON(none_as_null=True), nullable=False),
    sa.CheckConstraint('(fuzzy_lower IS NULL AND fuzzy_middle IS NULL AND fuzzy_upper IS NULL) OR (fuzzy_lower IS NOT NULL AND fuzzy_middle IS NOT NULL AND fuzzy_upper IS NOT NULL AND fuzzy_lower <= fuzzy_middle AND fuzzy_middle <= fuzzy_upper)', name='ck_scenario_scale_values_fuzzy_shape'),
    sa.CheckConstraint('ordinal >= 0', name='ck_scenario_scale_values_ordinal_nonnegative'),
    sa.ForeignKeyConstraint(['scale_id'], ['scenario_scales.scale_id'], name='fk_scenario_scale_values_scale_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scale_value_id', name=op.f('pk_scenario_scale_values')),
    sa.UniqueConstraint('scale_id', 'ordinal', name='uq_scenario_scale_values_scale_ordinal'),
    sa.UniqueConstraint('scale_id', 'stable_value_key', name='uq_scenario_scale_values_scale_key')
    )
    with op.batch_alter_table('scenario_scale_values', schema=None) as batch_op:
        batch_op.create_index('ix_scenario_scale_values_scale_id', ['scale_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario_scale_values', schema=None) as batch_op:
        batch_op.drop_index('ix_scenario_scale_values_scale_id')

    op.drop_table('scenario_scale_values')
    with op.batch_alter_table('scenario_matrix_values', schema=None) as batch_op:
        batch_op.drop_index('ix_scenario_matrix_values_criterion_id')
        batch_op.drop_index('ix_scenario_matrix_values_alternative_id')

    op.drop_table('scenario_matrix_values')
    with op.batch_alter_table('scenario_snapshot_files', schema=None) as batch_op:
        batch_op.drop_index('ix_scenario_snapshot_files_snapshot_role')
        batch_op.drop_index('ix_scenario_snapshot_files_content_hash')

    op.drop_table('scenario_snapshot_files')
    with op.batch_alter_table('scenario_scales', schema=None) as batch_op:
        batch_op.drop_index('ix_scenario_scales_snapshot_id')

    op.drop_table('scenario_scales')
    with op.batch_alter_table('scenario_criteria', schema=None) as batch_op:
        batch_op.drop_index('ix_scenario_criteria_snapshot_order')
        batch_op.drop_index('ix_scenario_criteria_parent_id')

    op.drop_table('scenario_criteria')
    with op.batch_alter_table('scenario_alternatives', schema=None) as batch_op:
        batch_op.drop_index('ix_scenario_alternatives_snapshot_order')

    op.drop_table('scenario_alternatives')
    with op.batch_alter_table('scenario_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_scenario_snapshots_status')
        batch_op.drop_index('ix_scenario_snapshots_definition_created')

    op.drop_table('scenario_snapshots')
    with op.batch_alter_table('scenario_definitions', schema=None) as batch_op:
        batch_op.drop_index('ix_scenario_definitions_status')
        batch_op.drop_index('ix_scenario_definitions_domain')

    op.drop_table('scenario_definitions')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_events_session_occurred')
        batch_op.drop_index('ix_audit_events_entity')
        batch_op.drop_index('ix_audit_events_correlation_id')
        batch_op.drop_index('ix_audit_events_causation_event_id')
        batch_op.drop_index('ix_audit_events_action_occurred')

    op.drop_table('audit_events')
    # ### end Alembic commands ###
