"""create session configuration tables

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-30 01:53:11.091675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from poli_insight.infrastructure.database.types import UTCDateTime
from poli_insight.infrastructure.database.types import UUIDString

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('algorithm_implementations',
    sa.Column('algorithm_implementation_id', UUIDString(), nullable=False),
    sa.Column('stable_key', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('conceptual_method', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('library_name', sa.String(length=100), nullable=False),
    sa.Column('library_version', sa.String(length=100), nullable=False),
    sa.Column('implementation_version', sa.String(length=100), nullable=False),
    sa.Column('adapter_version', sa.String(length=100), nullable=False),
    sa.Column('parameter_schema_json', sa.JSON(none_as_null=True), nullable=False),
    sa.Column('capabilities_json', sa.JSON(none_as_null=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.CheckConstraint("role IN ('weighting', 'within_group_aggregation', 'across_group_aggregation', 'ranking', 'validation', 'analysis')", name='ck_algorithm_impl_role_allowed'),
    sa.CheckConstraint("status IN ('active', 'retired')", name='ck_algorithm_impl_status_allowed'),
    sa.CheckConstraint('length(trim(implementation_version)) > 0', name='ck_algorithm_impl_version_nonempty'),
    sa.CheckConstraint('length(trim(provider)) > 0', name='ck_algorithm_impl_provider_nonempty'),
    sa.CheckConstraint('length(trim(stable_key)) > 0', name='ck_algorithm_impl_stable_key_nonempty'),
    sa.PrimaryKeyConstraint('algorithm_implementation_id', name=op.f('pk_algorithm_implementations')),
    sa.UniqueConstraint('algorithm_implementation_id', 'role', name='uq_algorithm_impl_id_role'),
    sa.UniqueConstraint('stable_key', 'provider', 'library_name', 'library_version', 'implementation_version', 'adapter_version', name='uq_algorithm_impl_version_identity')
    )
    with op.batch_alter_table('algorithm_implementations', schema=None) as batch_op:
        batch_op.create_index('ix_algorithm_impl_stable_role', ['stable_key', 'role'], unique=False)
        batch_op.create_index('ix_algorithm_impl_status', ['status'], unique=False)

    op.create_table('sessions',
    sa.Column('session_id', UUIDString(), nullable=False),
    sa.Column('scenario_snapshot_id', UUIDString(), nullable=False),
    sa.Column('public_slug', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('discoverability', sa.String(length=50), nullable=False),
    sa.Column('enrollment_mode', sa.String(length=50), nullable=False),
    sa.Column('access_code_mode', sa.String(length=50), nullable=False),
    sa.Column('identity_policy', sa.String(length=50), nullable=False),
    sa.Column('stakeholder_selection_mode', sa.String(length=50), nullable=False),
    sa.Column('opens_at', UTCDateTime(), nullable=True),
    sa.Column('closes_at', UTCDateTime(), nullable=True),
    sa.Column('opened_at', UTCDateTime(), nullable=True),
    sa.Column('paused_at', UTCDateTime(), nullable=True),
    sa.Column('closed_at', UTCDateTime(), nullable=True),
    sa.Column('canceled_at', UTCDateTime(), nullable=True),
    sa.Column('archived_at', UTCDateTime(), nullable=True),
    sa.Column('active_configuration_version_id', UUIDString(), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False),
    sa.CheckConstraint("access_code_mode <> 'per_invitation_code' OR enrollment_mode = 'invitation_only'", name='ck_sessions_invitation_code_requires_invite'),
    sa.CheckConstraint("access_code_mode IN ('none', 'shared_session_code', 'per_invitation_code')", name='ck_sessions_access_code_mode_allowed'),
    sa.CheckConstraint("discoverability IN ('listed', 'unlisted')", name='ck_sessions_discoverability_allowed'),
    sa.CheckConstraint("enrollment_mode IN ('open', 'invitation_only')", name='ck_sessions_enrollment_mode_allowed'),
    sa.CheckConstraint("stakeholder_selection_mode IN ('self_select', 'invitation_assigned', 'moderator_assigned')", name='ck_sessions_stakeholder_selection_allowed'),
    sa.CheckConstraint("status <> 'archived' OR (archived_at IS NOT NULL AND (closed_at IS NOT NULL OR canceled_at IS NOT NULL))", name='ck_sessions_archived_has_history'),
    sa.CheckConstraint("status <> 'canceled' OR canceled_at IS NOT NULL", name='ck_sessions_canceled_has_timestamp'),
    sa.CheckConstraint("status <> 'closed' OR closed_at IS NOT NULL", name='ck_sessions_closed_has_timestamp'),
    sa.CheckConstraint("status <> 'paused' OR paused_at IS NOT NULL", name='ck_sessions_paused_has_timestamp'),
    sa.CheckConstraint("status <> 'scheduled' OR opens_at IS NOT NULL", name='ck_sessions_scheduled_has_opens_at'),
    sa.CheckConstraint("status IN ('draft', 'scheduled', 'open', 'paused', 'closed', 'canceled', 'archived')", name='ck_sessions_status_allowed'),
    sa.CheckConstraint("status NOT IN ('open', 'paused', 'closed') OR opened_at IS NOT NULL", name='ck_sessions_active_history_has_opened_at'),
    sa.CheckConstraint('closes_at IS NULL OR opens_at IS NULL OR closes_at > opens_at', name='ck_sessions_schedule_order'),
    sa.CheckConstraint('length(trim(identity_policy)) > 0', name='ck_sessions_identity_policy_nonempty'),
    sa.CheckConstraint('length(trim(public_slug)) > 0', name='ck_sessions_public_slug_nonempty'),
    sa.CheckConstraint('length(trim(title)) > 0', name='ck_sessions_title_nonempty'),
    sa.CheckConstraint('updated_at >= created_at', name='ck_sessions_update_not_before_create'),
    sa.ForeignKeyConstraint(['scenario_snapshot_id'], ['scenario_snapshots.scenario_snapshot_id'], name='fk_sessions_scenario_snapshot_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id', 'active_configuration_version_id'], ['session_configuration_versions.session_id', 'session_configuration_versions.configuration_version_id'], name='fk_sessions_active_config_same_session', ondelete='RESTRICT', use_alter=True),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('public_slug', name='uq_sessions_public_slug')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('ix_sessions_active_configuration_id', ['active_configuration_version_id'], unique=False)
        batch_op.create_index('ix_sessions_closes_at', ['closes_at'], unique=False)
        batch_op.create_index('ix_sessions_opens_at', ['opens_at'], unique=False)
        batch_op.create_index('ix_sessions_scenario_snapshot_id', ['scenario_snapshot_id'], unique=False)
        batch_op.create_index('ix_sessions_status', ['status'], unique=False)

    op.create_table('session_configuration_versions',
    sa.Column('configuration_version_id', UUIDString(), nullable=False),
    sa.Column('session_id', UUIDString(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('scenario_snapshot_id', UUIDString(), nullable=False),
    sa.Column('response_format', sa.String(length=50), nullable=False),
    sa.Column('response_target_type', sa.String(length=50), nullable=False),
    sa.Column('scale_id', UUIDString(), nullable=False),
    sa.Column('allow_resubmissions', sa.Boolean(), nullable=False),
    sa.Column('max_submissions_per_participant', sa.Integer(), nullable=False),
    sa.Column('allow_incomplete_submission', sa.Boolean(), nullable=False),
    sa.Column('minimum_valid_submissions', sa.Integer(), nullable=False),
    sa.Column('missing_group_policy', sa.String(length=50), nullable=False),
    sa.Column('required_group_policy_json', sa.JSON(none_as_null=True), nullable=False),
    sa.Column('consistency_threshold', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('configuration_json', sa.JSON(none_as_null=True), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('allocation_total_units', sa.Integer(), server_default='10000', nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('activated_at', UTCDateTime(), nullable=True),
    sa.Column('activated_by', sa.String(length=100), nullable=True),
    sa.CheckConstraint("missing_group_policy IN ('fail', 'exclude_and_renormalize', 'zero_contribution')", name='ck_session_configs_missing_group_allowed'),
    sa.CheckConstraint("response_format IN ('pairwise', 'direct_rating', 'direct_ranking')", name='ck_session_configs_response_format_allowed'),
    sa.CheckConstraint("response_target_type IN ('criterion', 'alternative')", name='ck_session_configs_target_type_allowed'),
    sa.CheckConstraint('(NOT allow_resubmissions AND max_submissions_per_participant = 1) OR (allow_resubmissions AND max_submissions_per_participant >= 2)', name='ck_session_configs_resubmission_limit'),
    sa.CheckConstraint('(activated_at IS NULL AND activated_by IS NULL) OR (activated_at IS NOT NULL AND activated_by IS NOT NULL)', name='ck_session_configs_activation_pair'),
    sa.CheckConstraint('activated_at IS NULL OR activated_at >= created_at', name='ck_session_configs_activation_order'),
    sa.CheckConstraint('allocation_total_units > 0', name='ck_session_configs_allocation_total_positive'),
    sa.CheckConstraint('consistency_threshold IS NULL OR (consistency_threshold >= 0 AND consistency_threshold <= 1)', name='ck_session_configs_consistency_range'),
    sa.CheckConstraint('length(config_hash) = 64 AND config_hash = lower(config_hash)', name='ck_session_configs_hash_format'),
    sa.CheckConstraint('minimum_valid_submissions >= 1', name='ck_session_configs_minimum_valid_positive'),
    sa.CheckConstraint('schema_version >= 1', name='ck_session_configs_schema_version_positive'),
    sa.CheckConstraint('version_number >= 1', name='ck_session_configs_version_positive'),
    sa.ForeignKeyConstraint(['scale_id'], ['scenario_scales.scale_id'], name='fk_session_configs_scale_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scenario_snapshot_id'], ['scenario_snapshots.scenario_snapshot_id'], name='fk_session_configs_snapshot_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], name='fk_session_configs_session_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('configuration_version_id', name=op.f('pk_session_configuration_versions')),
    sa.UniqueConstraint('session_id', 'config_hash', name='uq_session_configs_session_hash'),
    sa.UniqueConstraint('session_id', 'configuration_version_id', name='uq_session_configs_session_id'),
    sa.UniqueConstraint('session_id', 'version_number', name='uq_session_configs_session_version')
    )
    with op.batch_alter_table('session_configuration_versions', schema=None) as batch_op:
        batch_op.create_index('ix_session_configs_scale_id', ['scale_id'], unique=False)
        batch_op.create_index('ix_session_configs_session_activated', ['session_id', 'activated_at'], unique=False)
        batch_op.create_index('ix_session_configs_snapshot_id', ['scenario_snapshot_id'], unique=False)

    op.create_table('response_question_definitions',
    sa.Column('question_definition_id', UUIDString(), nullable=False),
    sa.Column('configuration_version_id', UUIDString(), nullable=False),
    sa.Column('question_key', sa.String(length=160), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('criterion_id', UUIDString(), nullable=True),
    sa.Column('left_criterion_id', UUIDString(), nullable=True),
    sa.Column('right_criterion_id', UUIDString(), nullable=True),
    sa.Column('alternative_id', UUIDString(), nullable=True),
    sa.Column('scale_id', UUIDString(), nullable=True),
    sa.Column('prompt_snapshot', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(none_as_null=True), nullable=False),
    sa.CheckConstraint("(question_type = 'criterion_pair' AND criterion_id IS NULL AND left_criterion_id IS NOT NULL AND right_criterion_id IS NOT NULL AND left_criterion_id < right_criterion_id AND alternative_id IS NULL AND scale_id IS NOT NULL) OR (question_type = 'criterion_rating' AND criterion_id IS NOT NULL AND left_criterion_id IS NULL AND right_criterion_id IS NULL AND alternative_id IS NULL AND scale_id IS NOT NULL) OR (question_type = 'alternative_rating' AND criterion_id IS NULL AND left_criterion_id IS NULL AND right_criterion_id IS NULL AND alternative_id IS NOT NULL AND scale_id IS NOT NULL) OR (question_type = 'alternative_rank' AND criterion_id IS NULL AND left_criterion_id IS NULL AND right_criterion_id IS NULL AND alternative_id IS NOT NULL AND scale_id IS NULL)", name='ck_response_questions_target_shape'),
    sa.CheckConstraint("question_type IN ('criterion_pair', 'criterion_rating', 'alternative_rating', 'alternative_rank')", name='ck_response_questions_type_allowed'),
    sa.CheckConstraint('display_order >= 0', name='ck_response_questions_order_nonnegative'),
    sa.CheckConstraint('length(trim(prompt_snapshot)) > 0', name='ck_response_questions_prompt_nonempty'),
    sa.CheckConstraint('length(trim(question_key)) > 0', name='ck_response_questions_key_nonempty'),
    sa.ForeignKeyConstraint(['alternative_id'], ['scenario_alternatives.alternative_id'], name='fk_response_questions_alternative_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['configuration_version_id'], ['session_configuration_versions.configuration_version_id'], name='fk_response_questions_config_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['criterion_id'], ['scenario_criteria.criterion_id'], name='fk_response_questions_criterion_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['left_criterion_id'], ['scenario_criteria.criterion_id'], name='fk_response_questions_left_criterion_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['right_criterion_id'], ['scenario_criteria.criterion_id'], name='fk_response_questions_right_criterion_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scale_id'], ['scenario_scales.scale_id'], name='fk_response_questions_scale_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('question_definition_id', name=op.f('pk_response_question_definitions')),
    sa.UniqueConstraint('configuration_version_id', 'display_order', name='uq_response_questions_config_order'),
    sa.UniqueConstraint('configuration_version_id', 'left_criterion_id', 'right_criterion_id', name='uq_response_questions_config_pair'),
    sa.UniqueConstraint('configuration_version_id', 'question_key', name='uq_response_questions_config_key')
    )
    with op.batch_alter_table('response_question_definitions', schema=None) as batch_op:
        batch_op.create_index('ix_response_questions_alternative_id', ['alternative_id'], unique=False)
        batch_op.create_index('ix_response_questions_config_type', ['configuration_version_id', 'question_type'], unique=False)
        batch_op.create_index('ix_response_questions_criterion_id', ['criterion_id'], unique=False)

    op.create_table('session_algorithm_configs',
    sa.Column('session_algorithm_config_id', UUIDString(), nullable=False),
    sa.Column('configuration_version_id', UUIDString(), nullable=False),
    sa.Column('algorithm_implementation_id', UUIDString(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('execution_order', sa.Integer(), nullable=False),
    sa.Column('parameter_json', sa.JSON(none_as_null=True), nullable=False),
    sa.Column('parameter_schema_version', sa.Integer(), nullable=False),
    sa.Column('parameter_hash', sa.String(length=64), nullable=False),
    sa.CheckConstraint("role IN ('weighting', 'within_group_aggregation', 'across_group_aggregation', 'ranking', 'validation', 'analysis')", name='ck_session_algorithm_configs_role_allowed'),
    sa.CheckConstraint('execution_order >= 0', name='ck_session_algorithm_configs_order_nonnegative'),
    sa.CheckConstraint('length(parameter_hash) = 64 AND parameter_hash = lower(parameter_hash)', name='ck_session_algorithm_configs_hash_format'),
    sa.CheckConstraint('parameter_schema_version >= 1', name='ck_session_algorithm_configs_schema_positive'),
    sa.ForeignKeyConstraint(['algorithm_implementation_id', 'role'], ['algorithm_implementations.algorithm_implementation_id', 'algorithm_implementations.role'], name='fk_session_algorithm_configs_impl_role', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['configuration_version_id'], ['session_configuration_versions.configuration_version_id'], name='fk_session_algorithm_configs_config_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('session_algorithm_config_id', name=op.f('pk_session_algorithm_configs')),
    sa.UniqueConstraint('configuration_version_id', 'role', 'execution_order', name='uq_session_algorithm_configs_role_order'),
    sa.UniqueConstraint('configuration_version_id', 'session_algorithm_config_id', name='uq_session_algorithm_configs_config_id')
    )
    with op.batch_alter_table('session_algorithm_configs', schema=None) as batch_op:
        batch_op.create_index('ix_session_algorithm_configs_impl_id', ['algorithm_implementation_id'], unique=False)

    op.create_table('session_stakeholder_groups',
    sa.Column('session_stakeholder_group_id', UUIDString(), nullable=False),
    sa.Column('configuration_version_id', UUIDString(), nullable=False),
    sa.Column('group_key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('allocation_units', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('within_group_algorithm_config_id', UUIDString(), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.CheckConstraint('allocation_units >= 0', name='ck_session_groups_allocation_nonnegative'),
    sa.CheckConstraint('display_order >= 0', name='ck_session_groups_order_nonnegative'),
    sa.CheckConstraint('length(trim(group_key)) > 0', name='ck_session_groups_key_nonempty'),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_session_groups_name_nonempty'),
    sa.ForeignKeyConstraint(['configuration_version_id', 'within_group_algorithm_config_id'], ['session_algorithm_configs.configuration_version_id', 'session_algorithm_configs.session_algorithm_config_id'], name='fk_session_groups_within_algorithm', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['configuration_version_id'], ['session_configuration_versions.configuration_version_id'], name='fk_session_groups_config_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('session_stakeholder_group_id', name=op.f('pk_session_stakeholder_groups')),
    sa.UniqueConstraint('configuration_version_id', 'display_order', name='uq_session_groups_config_order'),
    sa.UniqueConstraint('configuration_version_id', 'group_key', name='uq_session_groups_config_key'),
    sa.UniqueConstraint('configuration_version_id', 'session_stakeholder_group_id', name='uq_session_groups_config_id')
    )
    with op.batch_alter_table('session_stakeholder_groups', schema=None) as batch_op:
        batch_op.create_index('ix_session_groups_config_active', ['configuration_version_id', 'is_active'], unique=False)
        batch_op.create_index('ix_session_groups_within_algorithm_id', ['within_group_algorithm_config_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_stakeholder_groups', schema=None) as batch_op:
        batch_op.drop_index('ix_session_groups_within_algorithm_id')
        batch_op.drop_index('ix_session_groups_config_active')

    op.drop_table('session_stakeholder_groups')
    with op.batch_alter_table('session_algorithm_configs', schema=None) as batch_op:
        batch_op.drop_index('ix_session_algorithm_configs_impl_id')

    op.drop_table('session_algorithm_configs')
    with op.batch_alter_table('response_question_definitions', schema=None) as batch_op:
        batch_op.drop_index('ix_response_questions_criterion_id')
        batch_op.drop_index('ix_response_questions_config_type')
        batch_op.drop_index('ix_response_questions_alternative_id')

    op.drop_table('response_question_definitions')
    with op.batch_alter_table('session_configuration_versions', schema=None) as batch_op:
        batch_op.drop_index('ix_session_configs_snapshot_id')
        batch_op.drop_index('ix_session_configs_session_activated')
        batch_op.drop_index('ix_session_configs_scale_id')

    op.drop_table('session_configuration_versions')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_status')
        batch_op.drop_index('ix_sessions_scenario_snapshot_id')
        batch_op.drop_index('ix_sessions_opens_at')
        batch_op.drop_index('ix_sessions_closes_at')
        batch_op.drop_index('ix_sessions_active_configuration_id')

    op.drop_table('sessions')
    with op.batch_alter_table('algorithm_implementations', schema=None) as batch_op:
        batch_op.drop_index('ix_algorithm_impl_status')
        batch_op.drop_index('ix_algorithm_impl_stable_role')

    op.drop_table('algorithm_implementations')
    # ### end Alembic commands ###
