"""create participation tables

Revision ID: 0003
Revises: 0002
Create Date: 2026-07-30 03:21:01.226949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from poli_insight.infrastructure.database.types import UTCDateTime
from poli_insight.infrastructure.database.types import UUIDString

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('participant_id', UUIDString(), nullable=False),
    sa.Column('session_id', UUIDString(), nullable=False),
    sa.Column('configuration_version_id', UUIDString(), nullable=False),
    sa.Column('session_stakeholder_group_id', UUIDString(), nullable=False),
    sa.Column('user_id', UUIDString(), nullable=True),
    sa.Column('invitation_id', UUIDString(), nullable=True),
    sa.Column('alias', sa.String(length=160), nullable=True),
    sa.Column('access_status', sa.String(length=50), server_default='active', nullable=False),
    sa.Column('enrolled_at', UTCDateTime(), nullable=False),
    sa.Column('joined_at', UTCDateTime(), nullable=True),
    sa.Column('started_at', UTCDateTime(), nullable=True),
    sa.Column('submitted_at', UTCDateTime(), nullable=True),
    sa.Column('completed_at', UTCDateTime(), nullable=True),
    sa.Column('disabled_at', UTCDateTime(), nullable=True),
    sa.Column('disabled_by', sa.String(length=100), nullable=True),
    sa.Column('disable_reason', sa.Text(), nullable=True),
    sa.Column('withdrawn_at', UTCDateTime(), nullable=True),
    sa.Column('withdrawn_by', sa.String(length=100), nullable=True),
    sa.Column('withdrawal_reason', sa.Text(), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False),
    sa.CheckConstraint("(access_status = 'active' AND disabled_at IS NULL AND disabled_by IS NULL AND disable_reason IS NULL AND withdrawn_at IS NULL AND withdrawn_by IS NULL AND withdrawal_reason IS NULL) OR (access_status = 'disabled' AND disabled_at IS NOT NULL AND disabled_by IS NOT NULL AND disable_reason IS NOT NULL AND withdrawn_at IS NULL AND withdrawn_by IS NULL AND withdrawal_reason IS NULL) OR (access_status = 'withdrawn' AND withdrawn_at IS NOT NULL AND withdrawn_by IS NOT NULL AND withdrawal_reason IS NOT NULL AND ((disabled_at IS NULL AND disabled_by IS NULL AND disable_reason IS NULL) OR (disabled_at IS NOT NULL AND disabled_by IS NOT NULL AND disable_reason IS NOT NULL)))", name='ck_participants_access_state'),
    sa.CheckConstraint("access_status IN ('active', 'disabled', 'withdrawn')", name='ck_participants_access_status_allowed'),
    sa.CheckConstraint('alias IS NULL OR length(trim(alias)) > 0', name='ck_participants_alias_nonempty'),
    sa.CheckConstraint('completed_at IS NULL OR (submitted_at IS NOT NULL AND completed_at >= submitted_at)', name='ck_participants_completion_order'),
    sa.CheckConstraint('disabled_at IS NULL OR disabled_at >= created_at', name='ck_participants_disable_order'),
    sa.CheckConstraint('enrolled_at >= created_at', name='ck_participants_enrollment_order'),
    sa.CheckConstraint('joined_at IS NULL OR joined_at >= enrolled_at', name='ck_participants_join_order'),
    sa.CheckConstraint('length(trim(created_by)) > 0', name='ck_participants_creator_nonempty'),
    sa.CheckConstraint('length(trim(updated_by)) > 0', name='ck_participants_updater_nonempty'),
    sa.CheckConstraint('started_at IS NULL OR (joined_at IS NOT NULL AND started_at >= joined_at)', name='ck_participants_start_order'),
    sa.CheckConstraint('submitted_at IS NULL OR (started_at IS NOT NULL AND submitted_at >= started_at)', name='ck_participants_submission_order'),
    sa.CheckConstraint('updated_at >= created_at', name='ck_participants_update_order'),
    sa.CheckConstraint('updated_at >= enrolled_at AND (joined_at IS NULL OR updated_at >= joined_at) AND (started_at IS NULL OR updated_at >= started_at) AND (submitted_at IS NULL OR updated_at >= submitted_at) AND (completed_at IS NULL OR updated_at >= completed_at) AND (disabled_at IS NULL OR updated_at >= disabled_at) AND (withdrawn_at IS NULL OR updated_at >= withdrawn_at)', name='ck_participants_update_after_events'),
    sa.CheckConstraint('withdrawn_at IS NULL OR withdrawn_at >= created_at', name='ck_participants_withdrawal_order'),
    sa.ForeignKeyConstraint(['configuration_version_id', 'session_stakeholder_group_id'], ['session_stakeholder_groups.configuration_version_id', 'session_stakeholder_groups.session_stakeholder_group_id'], name='fk_participants_configuration_group', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id', 'configuration_version_id', 'invitation_id'], ['session_invitations.session_id', 'session_invitations.configuration_version_id', 'session_invitations.invitation_id'], name='fk_participants_session_config_invitation', ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['session_id', 'configuration_version_id'], ['session_configuration_versions.session_id', 'session_configuration_versions.configuration_version_id'], name='fk_participants_session_configuration', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], name='fk_participants_session_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('participant_id', name=op.f('pk_participants')),
    sa.UniqueConstraint('invitation_id', name='uq_participants_invitation_id'),
    sa.UniqueConstraint('session_id', 'alias', name='uq_participants_session_alias'),
    sa.UniqueConstraint('session_id', 'invitation_id', 'participant_id', name='uq_participants_session_invitation_participant'),
    sa.UniqueConstraint('session_id', 'participant_id', name='uq_participants_session_id'),
    sa.UniqueConstraint('session_id', 'user_id', name='uq_participants_session_user')
    )
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.create_index('ix_participants_configuration_group', ['configuration_version_id', 'session_stakeholder_group_id'], unique=False)
        batch_op.create_index('ix_participants_session_access', ['session_id', 'access_status'], unique=False)
        batch_op.create_index('ix_participants_session_completed', ['session_id', 'completed_at'], unique=False)
        batch_op.create_index('ix_participants_session_started', ['session_id', 'started_at'], unique=False)

    op.create_table('session_invitations',
    sa.Column('invitation_id', UUIDString(), nullable=False),
    sa.Column('session_id', UUIDString(), nullable=False),
    sa.Column('configuration_version_id', UUIDString(), nullable=False),
    sa.Column('assigned_group_id', UUIDString(), nullable=True),
    sa.Column('token_digest', sa.String(length=64), nullable=False),
    sa.Column('token_hint', sa.String(length=32), nullable=True),
    sa.Column('identity_lookup_hash', sa.String(length=64), nullable=True),
    sa.Column('identity_ciphertext', sa.LargeBinary(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('expires_at', UTCDateTime(), nullable=False),
    sa.Column('max_redemptions', sa.Integer(), server_default='1', nullable=False),
    sa.Column('sent_at', UTCDateTime(), nullable=True),
    sa.Column('send_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('redeemed_at', UTCDateTime(), nullable=True),
    sa.Column('redeemed_participant_id', UUIDString(), nullable=True),
    sa.Column('revoked_at', UTCDateTime(), nullable=True),
    sa.Column('revoked_by', sa.String(length=100), nullable=True),
    sa.Column('revocation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.CheckConstraint("(status = 'redeemed' AND redeemed_at IS NOT NULL AND redeemed_participant_id IS NOT NULL) OR (status <> 'redeemed' AND redeemed_at IS NULL AND redeemed_participant_id IS NULL)", name='ck_invitations_redemption_state'),
    sa.CheckConstraint("(status = 'revoked' AND revoked_at IS NOT NULL AND revoked_by IS NOT NULL AND revocation_reason IS NOT NULL) OR (status <> 'revoked' AND revoked_at IS NULL AND revoked_by IS NULL AND revocation_reason IS NULL)", name='ck_invitations_revocation_state'),
    sa.CheckConstraint("(status IN ('sent', 'delivery_failed', 'redeemed') AND sent_at IS NOT NULL AND send_count >= 1) OR (status = 'pending' AND sent_at IS NULL AND send_count = 0) OR (status IN ('expired', 'revoked') AND ((sent_at IS NULL AND send_count = 0) OR (sent_at IS NOT NULL AND send_count >= 1)))", name='ck_invitations_send_state'),
    sa.CheckConstraint("status IN ('pending', 'sent', 'redeemed', 'expired', 'revoked', 'delivery_failed')", name='ck_invitations_status_allowed'),
    sa.CheckConstraint('expires_at > created_at', name='ck_invitations_expiration_order'),
    sa.CheckConstraint('identity_ciphertext IS NULL OR length(identity_ciphertext) > 0', name='ck_invitations_identity_ciphertext_nonempty'),
    sa.CheckConstraint('identity_lookup_hash IS NULL OR (length(identity_lookup_hash) = 64 AND identity_lookup_hash = lower(identity_lookup_hash))', name='ck_invitations_identity_hash_format'),
    sa.CheckConstraint('identity_lookup_hash IS NULL OR identity_ciphertext IS NOT NULL', name='ck_invitations_identity_hash_has_ciphertext'),
    sa.CheckConstraint('length(token_digest) = 64 AND token_digest = lower(token_digest)', name='ck_invitations_token_digest_format'),
    sa.CheckConstraint('length(trim(created_by)) > 0', name='ck_invitations_creator_nonempty'),
    sa.CheckConstraint('max_redemptions = 1', name='ck_invitations_one_time_redemption'),
    sa.CheckConstraint('redeemed_at IS NULL OR (redeemed_at >= created_at AND redeemed_at < expires_at)', name='ck_invitations_redemption_order'),
    sa.CheckConstraint('revoked_at IS NULL OR revoked_at >= created_at', name='ck_invitations_revocation_order'),
    sa.CheckConstraint('send_count >= 0', name='ck_invitations_send_count_nonnegative'),
    sa.CheckConstraint('sent_at IS NULL OR sent_at >= created_at', name='ck_invitations_send_order'),
    sa.CheckConstraint('token_hint IS NULL OR length(trim(token_hint)) > 0', name='ck_invitations_token_hint_nonempty'),
    sa.ForeignKeyConstraint(['configuration_version_id', 'assigned_group_id'], ['session_stakeholder_groups.configuration_version_id', 'session_stakeholder_groups.session_stakeholder_group_id'], name='fk_invitations_assigned_group', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id', 'configuration_version_id'], ['session_configuration_versions.session_id', 'session_configuration_versions.configuration_version_id'], name='fk_invitations_session_configuration', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id', 'invitation_id', 'redeemed_participant_id'], ['participants.session_id', 'participants.invitation_id', 'participants.participant_id'], name='fk_invitations_redeemed_participant', ondelete='RESTRICT', use_alter=True),
    sa.PrimaryKeyConstraint('invitation_id', name=op.f('pk_session_invitations')),
    sa.UniqueConstraint('session_id', 'configuration_version_id', 'invitation_id', name='uq_invitations_session_config_id'),
    sa.UniqueConstraint('token_digest', name='uq_session_invitations_token_digest')
    )
    with op.batch_alter_table('session_invitations', schema=None) as batch_op:
        batch_op.create_index('ix_invitations_assigned_group_id', ['assigned_group_id'], unique=False)
        batch_op.create_index('ix_invitations_configuration_id', ['configuration_version_id'], unique=False)
        batch_op.create_index('ix_invitations_expires_at', ['expires_at'], unique=False)
        batch_op.create_index('ix_invitations_identity_lookup_hash', ['identity_lookup_hash'], unique=False)
        batch_op.create_index('ix_invitations_session_status', ['session_id', 'status'], unique=False)

    op.create_table('participant_access_grants',
    sa.Column('access_grant_id', UUIDString(), nullable=False),
    sa.Column('participant_id', UUIDString(), nullable=False),
    sa.Column('token_digest', sa.String(length=64), nullable=False),
    sa.Column('issued_at', UTCDateTime(), nullable=False),
    sa.Column('expires_at', UTCDateTime(), nullable=False),
    sa.Column('last_used_at', UTCDateTime(), nullable=True),
    sa.Column('revoked_at', UTCDateTime(), nullable=True),
    sa.Column('revoked_by', sa.String(length=100), nullable=True),
    sa.Column('revocation_reason', sa.Text(), nullable=True),
    sa.Column('replaced_by_grant_id', UUIDString(), nullable=True),
    sa.CheckConstraint('(revoked_at IS NULL AND revoked_by IS NULL AND revocation_reason IS NULL) OR (revoked_at IS NOT NULL AND revoked_by IS NOT NULL AND revocation_reason IS NOT NULL AND revoked_at >= issued_at AND (last_used_at IS NULL OR revoked_at >= last_used_at))', name='ck_access_grants_revocation_state'),
    sa.CheckConstraint('expires_at > issued_at', name='ck_access_grants_expiration_order'),
    sa.CheckConstraint('last_used_at IS NULL OR (last_used_at >= issued_at AND last_used_at < expires_at)', name='ck_access_grants_last_use_order'),
    sa.CheckConstraint('length(token_digest) = 64 AND token_digest = lower(token_digest)', name='ck_access_grants_token_digest_format'),
    sa.CheckConstraint('replaced_by_grant_id IS NULL OR (revoked_at IS NOT NULL AND replaced_by_grant_id <> access_grant_id)', name='ck_access_grants_replacement_state'),
    sa.ForeignKeyConstraint(['participant_id', 'replaced_by_grant_id'], ['participant_access_grants.participant_id', 'participant_access_grants.access_grant_id'], name='fk_access_grants_same_participant_replacement', ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.participant_id'], name='fk_access_grants_participant_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('access_grant_id', name=op.f('pk_participant_access_grants')),
    sa.UniqueConstraint('participant_id', 'access_grant_id', name='uq_access_grants_participant_id'),
    sa.UniqueConstraint('token_digest', name='uq_participant_access_grants_token_digest')
    )
    with op.batch_alter_table('participant_access_grants', schema=None) as batch_op:
        batch_op.create_index('ix_access_grants_expires_at', ['expires_at'], unique=False)
        batch_op.create_index('ix_access_grants_participant_active', ['participant_id', 'revoked_at', 'expires_at'], unique=False)

    op.create_table('participant_identities',
    sa.Column('participant_id', UUIDString(), nullable=False),
    sa.Column('consent_version', sa.String(length=100), nullable=False),
    sa.Column('consented_at', UTCDateTime(), nullable=False),
    sa.Column('retention_until', UTCDateTime(), nullable=False),
    sa.Column('display_name_ciphertext', sa.LargeBinary(), nullable=True),
    sa.Column('email_ciphertext', sa.LargeBinary(), nullable=True),
    sa.Column('email_lookup_hash', sa.String(length=64), nullable=True),
    sa.Column('additional_identity_ciphertext', sa.LargeBinary(), nullable=True),
    sa.Column('redacted_at', UTCDateTime(), nullable=True),
    sa.Column('redacted_by', sa.String(length=100), nullable=True),
    sa.CheckConstraint('(email_ciphertext IS NULL AND email_lookup_hash IS NULL) OR (email_ciphertext IS NOT NULL AND email_lookup_hash IS NOT NULL)', name='ck_participant_identities_email_pair'),
    sa.CheckConstraint('(redacted_at IS NULL AND redacted_by IS NULL AND (display_name_ciphertext IS NOT NULL OR email_ciphertext IS NOT NULL OR additional_identity_ciphertext IS NOT NULL)) OR (redacted_at IS NOT NULL AND redacted_by IS NOT NULL AND redacted_at >= consented_at AND display_name_ciphertext IS NULL AND email_ciphertext IS NULL AND email_lookup_hash IS NULL AND additional_identity_ciphertext IS NULL)', name='ck_participant_identities_redaction_state'),
    sa.CheckConstraint('additional_identity_ciphertext IS NULL OR length(additional_identity_ciphertext) > 0', name='ck_participant_identities_extra_nonempty'),
    sa.CheckConstraint('display_name_ciphertext IS NULL OR length(display_name_ciphertext) > 0', name='ck_participant_identities_name_nonempty'),
    sa.CheckConstraint('email_ciphertext IS NULL OR length(email_ciphertext) > 0', name='ck_participant_identities_email_nonempty'),
    sa.CheckConstraint('email_lookup_hash IS NULL OR (length(email_lookup_hash) = 64 AND email_lookup_hash = lower(email_lookup_hash))', name='ck_participant_identities_email_hash_format'),
    sa.CheckConstraint('length(trim(consent_version)) > 0', name='ck_participant_identities_consent_nonempty'),
    sa.CheckConstraint('retention_until > consented_at', name='ck_participant_identities_retention_order'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.participant_id'], name='fk_participant_identities_participant_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('participant_id', name=op.f('pk_participant_identities'))
    )
    with op.batch_alter_table('participant_identities', schema=None) as batch_op:
        batch_op.create_index('ix_participant_identities_email_lookup_hash', ['email_lookup_hash'], unique=False)
        batch_op.create_index('ix_participant_identities_retention_until', ['retention_until'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant_identities', schema=None) as batch_op:
        batch_op.drop_index('ix_participant_identities_retention_until')
        batch_op.drop_index('ix_participant_identities_email_lookup_hash')

    op.drop_table('participant_identities')
    with op.batch_alter_table('participant_access_grants', schema=None) as batch_op:
        batch_op.drop_index('ix_access_grants_participant_active')
        batch_op.drop_index('ix_access_grants_expires_at')

    op.drop_table('participant_access_grants')
    with op.batch_alter_table('session_invitations', schema=None) as batch_op:
        batch_op.drop_index('ix_invitations_session_status')
        batch_op.drop_index('ix_invitations_identity_lookup_hash')
        batch_op.drop_index('ix_invitations_expires_at')
        batch_op.drop_index('ix_invitations_configuration_id')
        batch_op.drop_index('ix_invitations_assigned_group_id')

    op.drop_table('session_invitations')
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_index('ix_participants_session_started')
        batch_op.drop_index('ix_participants_session_completed')
        batch_op.drop_index('ix_participants_session_access')
        batch_op.drop_index('ix_participants_configuration_group')

    op.drop_table('participants')
    # ### end Alembic commands ###
