"""create submission tables

Revision ID: 0004
Revises: 0003
Create Date: 2026-07-30 04:59:00.179348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from poli_insight.infrastructure.database.types import UTCDateTime
from poli_insight.infrastructure.database.types import UUIDString

# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('submission_id', UUIDString(), nullable=False),
    sa.Column('session_id', UUIDString(), nullable=False),
    sa.Column('participant_id', UUIDString(), nullable=False),
    sa.Column('configuration_version_id', UUIDString(), nullable=False),
    sa.Column('scenario_snapshot_id', UUIDString(), nullable=False),
    sa.Column('session_stakeholder_group_id', UUIDString(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('previous_submission_id', UUIDString(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='draft', nullable=False),
    sa.Column('response_format', sa.String(length=50), nullable=False),
    sa.Column('response_target_type', sa.String(length=50), nullable=False),
    sa.Column('answer_manifest_json', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('answer_schema_version', sa.Integer(), nullable=True),
    sa.Column('answers_hash', sa.String(length=64), nullable=True),
    sa.Column('started_at', UTCDateTime(), nullable=False),
    sa.Column('last_saved_at', UTCDateTime(), nullable=False),
    sa.Column('submitted_at', UTCDateTime(), nullable=True),
    sa.Column('submitted_by', sa.String(length=100), nullable=True),
    sa.Column('superseded_at', UTCDateTime(), nullable=True),
    sa.Column('superseded_by', sa.String(length=100), nullable=True),
    sa.Column('withdrawn_at', UTCDateTime(), nullable=True),
    sa.Column('withdrawn_by', sa.String(length=100), nullable=True),
    sa.Column('withdrawal_reason', sa.Text(), nullable=True),
    sa.Column('client_metadata_json', sa.JSON(none_as_null=True), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False),
    sa.CheckConstraint("(status = 'draft' AND answer_manifest_json IS NULL AND answer_schema_version IS NULL AND answers_hash IS NULL AND submitted_at IS NULL AND submitted_by IS NULL) OR (status <> 'draft' AND answer_manifest_json IS NOT NULL AND answer_schema_version IS NOT NULL AND answers_hash IS NOT NULL AND submitted_at IS NOT NULL AND submitted_by IS NOT NULL)", name='ck_submissions_finalization_state'),
    sa.CheckConstraint("(status = 'superseded' AND superseded_at IS NOT NULL AND superseded_by IS NOT NULL) OR (status <> 'superseded' AND superseded_at IS NULL AND superseded_by IS NULL)", name='ck_submissions_supersession_state'),
    sa.CheckConstraint("(status = 'withdrawn' AND withdrawn_at IS NOT NULL AND withdrawn_by IS NOT NULL AND withdrawal_reason IS NOT NULL) OR (status <> 'withdrawn' AND withdrawn_at IS NULL AND withdrawn_by IS NULL AND withdrawal_reason IS NULL)", name='ck_submissions_withdrawal_state'),
    sa.CheckConstraint("response_format IN ('pairwise', 'direct_rating', 'direct_ranking')", name='ck_submissions_response_format_allowed'),
    sa.CheckConstraint("response_target_type IN ('criterion', 'alternative')", name='ck_submissions_target_type_allowed'),
    sa.CheckConstraint("status IN ('draft', 'submitted', 'superseded', 'withdrawn')", name='ck_submissions_status_allowed'),
    sa.CheckConstraint('(attempt_number = 1 AND previous_submission_id IS NULL) OR (attempt_number > 1 AND previous_submission_id IS NOT NULL)', name='ck_submissions_predecessor_shape'),
    sa.CheckConstraint('answer_schema_version IS NULL OR answer_schema_version >= 1', name='ck_submissions_answer_schema_positive'),
    sa.CheckConstraint('answers_hash IS NULL OR (length(answers_hash) = 64 AND answers_hash = lower(answers_hash))', name='ck_submissions_answers_hash_format'),
    sa.CheckConstraint('attempt_number >= 1', name='ck_submissions_attempt_positive'),
    sa.CheckConstraint('last_saved_at >= started_at', name='ck_submissions_save_order'),
    sa.CheckConstraint('length(trim(created_by)) > 0', name='ck_submissions_creator_nonempty'),
    sa.CheckConstraint('length(trim(updated_by)) > 0', name='ck_submissions_updater_nonempty'),
    sa.CheckConstraint('previous_submission_id IS NULL OR previous_submission_id <> submission_id', name='ck_submissions_predecessor_not_self'),
    sa.CheckConstraint('started_at >= created_at', name='ck_submissions_start_order'),
    sa.CheckConstraint('submitted_at IS NULL OR submitted_at = last_saved_at', name='ck_submissions_submit_freezes_save_time'),
    sa.CheckConstraint('submitted_by IS NULL OR length(trim(submitted_by)) > 0', name='ck_submissions_submitter_nonempty'),
    sa.CheckConstraint('superseded_at IS NULL OR (submitted_at IS NOT NULL AND superseded_at >= submitted_at)', name='ck_submissions_supersession_order'),
    sa.CheckConstraint('superseded_by IS NULL OR length(trim(superseded_by)) > 0', name='ck_submissions_superseder_nonempty'),
    sa.CheckConstraint('updated_at >= last_saved_at', name='ck_submissions_update_order'),
    sa.CheckConstraint('withdrawal_reason IS NULL OR length(trim(withdrawal_reason)) > 0', name='ck_submissions_withdrawal_reason_nonempty'),
    sa.CheckConstraint('withdrawn_at IS NULL OR (submitted_at IS NOT NULL AND withdrawn_at >= submitted_at)', name='ck_submissions_withdrawal_order'),
    sa.CheckConstraint('withdrawn_by IS NULL OR length(trim(withdrawn_by)) > 0', name='ck_submissions_withdrawer_nonempty'),
    sa.ForeignKeyConstraint(['configuration_version_id', 'session_stakeholder_group_id'], ['session_stakeholder_groups.configuration_version_id', 'session_stakeholder_groups.session_stakeholder_group_id'], name='fk_submissions_configuration_group', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['participant_id', 'configuration_version_id', 'previous_submission_id'], ['submissions.participant_id', 'submissions.configuration_version_id', 'submissions.submission_id'], name='fk_submissions_same_scope_predecessor', ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['scenario_snapshot_id'], ['scenario_snapshots.scenario_snapshot_id'], name='fk_submissions_scenario_snapshot_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id', 'configuration_version_id'], ['session_configuration_versions.session_id', 'session_configuration_versions.configuration_version_id'], name='fk_submissions_session_configuration', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id', 'participant_id'], ['participants.session_id', 'participants.participant_id'], name='fk_submissions_session_participant', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('submission_id', name=op.f('pk_submissions')),
    sa.UniqueConstraint('participant_id', 'attempt_number', name='uq_submissions_participant_attempt'),
    sa.UniqueConstraint('participant_id', 'configuration_version_id', 'submission_id', name='uq_submissions_participant_config_id')
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index('ix_submissions_configuration_group', ['configuration_version_id', 'session_stakeholder_group_id'], unique=False)
        batch_op.create_index('ix_submissions_participant_status', ['participant_id', 'status'], unique=False)
        batch_op.create_index('ix_submissions_previous_id', ['previous_submission_id'], unique=False)
        batch_op.create_index('ix_submissions_session_status', ['session_id', 'status'], unique=False)
        batch_op.create_index('ix_submissions_submitted_at', ['submitted_at'], unique=False)
        batch_op.create_index('uq_submissions_participant_draft', ['participant_id'], unique=True, postgresql_where=sa.text("status = 'draft'"), sqlite_where=sa.text("status = 'draft'"))
        batch_op.create_index('uq_submissions_participant_effective', ['participant_id'], unique=True, postgresql_where=sa.text("status = 'submitted'"), sqlite_where=sa.text("status = 'submitted'"))

    op.create_table('submission_answers',
    sa.Column('submission_answer_id', UUIDString(), nullable=False),
    sa.Column('submission_id', UUIDString(), nullable=False),
    sa.Column('question_definition_id', UUIDString(), nullable=False),
    sa.Column('raw_value_json', sa.JSON(none_as_null=True), nullable=False),
    sa.Column('value_schema_version', sa.Integer(), nullable=False),
    sa.Column('raw_value_hash', sa.String(length=64), nullable=False),
    sa.Column('selected_scale_value_id', UUIDString(), nullable=True),
    sa.Column('numeric_value', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('rank_value', sa.Integer(), nullable=True),
    sa.Column('answered_at', UTCDateTime(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.CheckConstraint('(selected_scale_value_id IS NOT NULL AND numeric_value IS NULL AND rank_value IS NULL) OR (selected_scale_value_id IS NULL AND numeric_value IS NOT NULL AND rank_value IS NULL) OR (selected_scale_value_id IS NULL AND numeric_value IS NULL AND rank_value IS NOT NULL)', name='ck_submission_answers_typed_value_shape'),
    sa.CheckConstraint('length(raw_value_hash) = 64 AND raw_value_hash = lower(raw_value_hash)', name='ck_submission_answers_hash_format'),
    sa.CheckConstraint('rank_value IS NULL OR rank_value >= 1', name='ck_submission_answers_rank_positive'),
    sa.CheckConstraint('response_time_ms IS NULL OR response_time_ms >= 0', name='ck_submission_answers_response_time_nonnegative'),
    sa.CheckConstraint('value_schema_version >= 1', name='ck_submission_answers_schema_positive'),
    sa.ForeignKeyConstraint(['question_definition_id'], ['response_question_definitions.question_definition_id'], name='fk_submission_answers_question_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['selected_scale_value_id'], ['scenario_scale_values.scale_value_id'], name='fk_submission_answers_scale_value_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submission_id'], name='fk_submission_answers_submission_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('submission_answer_id', name=op.f('pk_submission_answers')),
    sa.UniqueConstraint('submission_id', 'question_definition_id', name='uq_submission_answers_submission_question')
    )
    with op.batch_alter_table('submission_answers', schema=None) as batch_op:
        batch_op.create_index('ix_submission_answers_question_id', ['question_definition_id'], unique=False)
        batch_op.create_index('ix_submission_answers_scale_value_id', ['selected_scale_value_id'], unique=False)

    op.create_table('submission_comments',
    sa.Column('submission_comment_id', UUIDString(), nullable=False),
    sa.Column('submission_id', UUIDString(), nullable=False),
    sa.Column('criterion_id', UUIDString(), nullable=True),
    sa.Column('alternative_id', UUIDString(), nullable=True),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('audience', sa.String(length=50), nullable=False),
    sa.Column('moderation_status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('redacted_text', sa.Text(), nullable=True),
    sa.Column('redacted_at', UTCDateTime(), nullable=True),
    sa.Column('redacted_by', sa.String(length=100), nullable=True),
    sa.Column('redaction_reason', sa.Text(), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.CheckConstraint("(moderation_status = 'redacted' AND redacted_text IS NOT NULL AND redacted_at IS NOT NULL AND redacted_by IS NOT NULL AND redaction_reason IS NOT NULL) OR (moderation_status <> 'redacted' AND redacted_text IS NULL AND redacted_at IS NULL AND redacted_by IS NULL AND redaction_reason IS NULL)", name='ck_submission_comments_redaction_state'),
    sa.CheckConstraint("moderation_status IN ('pending', 'approved', 'rejected', 'redacted')", name='ck_submission_comments_moderation_allowed'),
    sa.CheckConstraint('criterion_id IS NULL OR alternative_id IS NULL', name='ck_submission_comments_single_target'),
    sa.CheckConstraint('length(trim(audience)) > 0', name='ck_submission_comments_audience_nonempty'),
    sa.CheckConstraint('length(trim(comment_text)) > 0', name='ck_submission_comments_text_nonempty'),
    sa.CheckConstraint('redacted_at IS NULL OR redacted_at >= created_at', name='ck_submission_comments_redaction_order'),
    sa.CheckConstraint('redacted_by IS NULL OR length(trim(redacted_by)) > 0', name='ck_submission_comments_redactor_nonempty'),
    sa.CheckConstraint('redacted_text IS NULL OR length(trim(redacted_text)) > 0', name='ck_submission_comments_redacted_text_nonempty'),
    sa.CheckConstraint('redaction_reason IS NULL OR length(trim(redaction_reason)) > 0', name='ck_submission_comments_redaction_reason_nonempty'),
    sa.ForeignKeyConstraint(['alternative_id'], ['scenario_alternatives.alternative_id'], name='fk_submission_comments_alternative_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['criterion_id'], ['scenario_criteria.criterion_id'], name='fk_submission_comments_criterion_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submission_id'], name='fk_submission_comments_submission_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('submission_comment_id', name=op.f('pk_submission_comments'))
    )
    with op.batch_alter_table('submission_comments', schema=None) as batch_op:
        batch_op.create_index('ix_submission_comments_alternative_id', ['alternative_id'], unique=False)
        batch_op.create_index('ix_submission_comments_criterion_id', ['criterion_id'], unique=False)
        batch_op.create_index('ix_submission_comments_moderation_status', ['moderation_status'], unique=False)
        batch_op.create_index('ix_submission_comments_submission_id', ['submission_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_comments', schema=None) as batch_op:
        batch_op.drop_index('ix_submission_comments_submission_id')
        batch_op.drop_index('ix_submission_comments_moderation_status')
        batch_op.drop_index('ix_submission_comments_criterion_id')
        batch_op.drop_index('ix_submission_comments_alternative_id')

    op.drop_table('submission_comments')
    with op.batch_alter_table('submission_answers', schema=None) as batch_op:
        batch_op.drop_index('ix_submission_answers_scale_value_id')
        batch_op.drop_index('ix_submission_answers_question_id')

    op.drop_table('submission_answers')
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index('uq_submissions_participant_effective', postgresql_where=sa.text("status = 'submitted'"), sqlite_where=sa.text("status = 'submitted'"))
        batch_op.drop_index('uq_submissions_participant_draft', postgresql_where=sa.text("status = 'draft'"), sqlite_where=sa.text("status = 'draft'"))
        batch_op.drop_index('ix_submissions_submitted_at')
        batch_op.drop_index('ix_submissions_session_status')
        batch_op.drop_index('ix_submissions_previous_id')
        batch_op.drop_index('ix_submissions_participant_status')
        batch_op.drop_index('ix_submissions_configuration_group')

    op.drop_table('submissions')
    # ### end Alembic commands ###
