"""create validation tables

Revision ID: 0005
Revises: 0004
Create Date: 2026-07-30 15:00:20.247468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from poli_insight.infrastructure.database.types import UTCDateTime
from poli_insight.infrastructure.database.types import UUIDString

# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission_validations',
    sa.Column('validation_id', UUIDString(), nullable=False),
    sa.Column('submission_id', UUIDString(), nullable=False),
    sa.Column('answers_hash', sa.String(length=64), nullable=False),
    sa.Column('configuration_hash', sa.String(length=64), nullable=False),
    sa.Column('validator_implementation_id', UUIDString(), nullable=False),
    sa.Column('validator_version', sa.String(length=100), nullable=False),
    sa.Column('parameter_json', sa.JSON(none_as_null=True), nullable=False),
    sa.Column('parameter_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('completion_ratio', sa.Numeric(precision=38, scale=18), server_default='0', nullable=False),
    sa.Column('consistency_ratio', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('quality_metrics_json', sa.JSON(none_as_null=True), nullable=False),
    sa.Column('started_at', UTCDateTime(), nullable=True),
    sa.Column('completed_at', UTCDateTime(), nullable=True),
    sa.Column('validated_by_actor_type', sa.String(length=50), nullable=True),
    sa.Column('validated_by_actor_id', sa.String(length=100), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('output_hash', sa.String(length=64), nullable=True),
    sa.Column('failure_code', sa.String(length=100), nullable=True),
    sa.Column('failure_detail', sa.Text(), nullable=True),
    sa.CheckConstraint("(status = 'pending' AND started_at IS NULL AND completed_at IS NULL AND validated_by_actor_type IS NULL AND validated_by_actor_id IS NULL AND output_hash IS NULL AND failure_code IS NULL AND failure_detail IS NULL AND completion_ratio = 0 AND consistency_ratio IS NULL) OR (status = 'running' AND started_at IS NOT NULL AND completed_at IS NULL AND validated_by_actor_type IS NULL AND validated_by_actor_id IS NULL AND output_hash IS NULL AND failure_code IS NULL AND failure_detail IS NULL AND completion_ratio = 0 AND consistency_ratio IS NULL) OR (status IN ('valid', 'valid_with_warnings', 'invalid') AND started_at IS NOT NULL AND completed_at IS NOT NULL AND validated_by_actor_type IS NOT NULL AND validated_by_actor_id IS NOT NULL AND output_hash IS NOT NULL AND failure_code IS NULL AND failure_detail IS NULL) OR (status = 'error' AND started_at IS NOT NULL AND completed_at IS NOT NULL AND validated_by_actor_type IS NOT NULL AND validated_by_actor_id IS NOT NULL AND output_hash IS NOT NULL AND failure_code IS NOT NULL AND failure_detail IS NOT NULL AND consistency_ratio IS NULL)", name='ck_submission_validations_lifecycle_state'),
    sa.CheckConstraint("status IN ('pending', 'running', 'valid', 'valid_with_warnings', 'invalid', 'error')", name='ck_submission_validations_status_allowed'),
    sa.CheckConstraint("validated_by_actor_type IS NULL OR validated_by_actor_type IN ('user', 'participant', 'system', 'ai_service', 'import_process', 'api_client')", name='ck_submission_validations_actor_type_allowed'),
    sa.CheckConstraint('completed_at IS NULL OR (started_at IS NOT NULL AND completed_at >= started_at)', name='ck_submission_validations_completion_order'),
    sa.CheckConstraint('completion_ratio >= 0 AND completion_ratio <= 1', name='ck_submission_validations_completion_range'),
    sa.CheckConstraint('consistency_ratio IS NULL OR consistency_ratio >= 0', name='ck_submission_validations_consistency_nonnegative'),
    sa.CheckConstraint('failure_code IS NULL OR length(trim(failure_code)) > 0', name='ck_submission_validations_failure_code_nonempty'),
    sa.CheckConstraint('failure_detail IS NULL OR length(trim(failure_detail)) > 0', name='ck_submission_validations_failure_detail_nonempty'),
    sa.CheckConstraint('length(answers_hash) = 64 AND answers_hash = lower(answers_hash)', name='ck_submission_validations_answers_hash_format'),
    sa.CheckConstraint('length(configuration_hash) = 64 AND configuration_hash = lower(configuration_hash)', name='ck_submission_validations_config_hash_format'),
    sa.CheckConstraint('length(input_hash) = 64 AND input_hash = lower(input_hash)', name='ck_submission_validations_input_hash_format'),
    sa.CheckConstraint('length(parameter_hash) = 64 AND parameter_hash = lower(parameter_hash)', name='ck_submission_validations_parameter_hash_format'),
    sa.CheckConstraint('length(trim(validator_version)) > 0', name='ck_submission_validations_version_nonempty'),
    sa.CheckConstraint('output_hash IS NULL OR (length(output_hash) = 64 AND output_hash = lower(output_hash))', name='ck_submission_validations_output_hash_format'),
    sa.CheckConstraint('validated_by_actor_id IS NULL OR length(trim(validated_by_actor_id)) > 0', name='ck_submission_validations_actor_id_nonempty'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submission_id'], name='fk_submission_validations_submission_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['validator_implementation_id'], ['algorithm_implementations.algorithm_implementation_id'], name='fk_submission_validations_validator_impl_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('validation_id', name=op.f('pk_submission_validations')),
    sa.UniqueConstraint('submission_id', 'answers_hash', 'configuration_hash', 'validator_implementation_id', 'validator_version', 'parameter_hash', name='uq_submission_validations_input_identity'),
    sa.UniqueConstraint('submission_id', 'validation_id', name='uq_submission_validations_submission_id')
    )
    with op.batch_alter_table('submission_validations', schema=None) as batch_op:
        batch_op.create_index('ix_submission_validations_completed_at', ['completed_at'], unique=False)
        batch_op.create_index('ix_submission_validations_implementation_id', ['validator_implementation_id'], unique=False)
        batch_op.create_index('ix_submission_validations_input_hash', ['input_hash'], unique=False)
        batch_op.create_index('ix_submission_validations_submission_status', ['submission_id', 'status'], unique=False)

    op.create_table('participant_criterion_weights',
    sa.Column('validation_id', UUIDString(), nullable=False),
    sa.Column('criterion_id', UUIDString(), nullable=False),
    sa.Column('crisp_weight', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('fuzzy_lower', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('fuzzy_middle', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('fuzzy_upper', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('derivation_metadata_json', sa.JSON(none_as_null=True), nullable=False),
    sa.CheckConstraint('(crisp_weight IS NOT NULL AND fuzzy_lower IS NULL AND fuzzy_middle IS NULL AND fuzzy_upper IS NULL) OR (crisp_weight IS NULL AND fuzzy_lower IS NOT NULL AND fuzzy_middle IS NOT NULL AND fuzzy_upper IS NOT NULL)', name='ck_participant_criterion_weights_value_shape'),
    sa.CheckConstraint('crisp_weight IS NULL OR crisp_weight >= 0', name='ck_participant_criterion_weights_crisp_nonnegative'),
    sa.CheckConstraint('fuzzy_lower IS NULL OR (fuzzy_lower <= fuzzy_middle AND fuzzy_middle <= fuzzy_upper)', name='ck_participant_criterion_weights_fuzzy_order'),
    sa.CheckConstraint('fuzzy_lower IS NULL OR (fuzzy_lower >= 0 AND fuzzy_middle >= 0 AND fuzzy_upper >= 0)', name='ck_participant_criterion_weights_fuzzy_nonnegative'),
    sa.ForeignKeyConstraint(['criterion_id'], ['scenario_criteria.criterion_id'], name='fk_participant_criterion_weights_criterion_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['validation_id'], ['submission_validations.validation_id'], name='fk_participant_criterion_weights_validation_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('validation_id', 'criterion_id', name=op.f('pk_participant_criterion_weights'))
    )
    with op.batch_alter_table('participant_criterion_weights', schema=None) as batch_op:
        batch_op.create_index('ix_participant_criterion_weights_criterion_id', ['criterion_id'], unique=False)

    op.create_table('validation_messages',
    sa.Column('validation_message_id', UUIDString(), nullable=False),
    sa.Column('validation_id', UUIDString(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=160), nullable=False),
    sa.Column('question_definition_id', UUIDString(), nullable=True),
    sa.Column('safe_message', sa.Text(), nullable=False),
    sa.Column('parameters_json', sa.JSON(none_as_null=True), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.CheckConstraint("severity IN ('info', 'warning', 'error')", name='ck_validation_messages_severity_allowed'),
    sa.CheckConstraint('display_order >= 0', name='ck_validation_messages_order_nonnegative'),
    sa.CheckConstraint('length(trim(code)) > 0 AND code = lower(code)', name='ck_validation_messages_code_format'),
    sa.CheckConstraint('length(trim(safe_message)) > 0', name='ck_validation_messages_safe_message_nonempty'),
    sa.ForeignKeyConstraint(['question_definition_id'], ['response_question_definitions.question_definition_id'], name='fk_validation_messages_question_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['validation_id'], ['submission_validations.validation_id'], name='fk_validation_messages_validation_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('validation_message_id', name=op.f('pk_validation_messages')),
    sa.UniqueConstraint('validation_id', 'display_order', name='uq_validation_messages_validation_order')
    )
    with op.batch_alter_table('validation_messages', schema=None) as batch_op:
        batch_op.create_index('ix_validation_messages_question_id', ['question_definition_id'], unique=False)
        batch_op.create_index('ix_validation_messages_validation_severity', ['validation_id', 'severity'], unique=False)

    op.create_table('validation_normalized_answers',
    sa.Column('validation_id', UUIDString(), nullable=False),
    sa.Column('submission_answer_id', UUIDString(), nullable=False),
    sa.Column('normalized_value_json', sa.JSON(none_as_null=True), nullable=False),
    sa.Column('normalizer_version', sa.String(length=100), nullable=False),
    sa.Column('crisp_value', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('fuzzy_lower', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('fuzzy_middle', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('fuzzy_upper', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.CheckConstraint('(crisp_value IS NOT NULL AND fuzzy_lower IS NULL AND fuzzy_middle IS NULL AND fuzzy_upper IS NULL) OR (crisp_value IS NULL AND fuzzy_lower IS NOT NULL AND fuzzy_middle IS NOT NULL AND fuzzy_upper IS NOT NULL) OR (crisp_value IS NULL AND fuzzy_lower IS NULL AND fuzzy_middle IS NULL AND fuzzy_upper IS NULL)', name='ck_validation_normalized_answers_numeric_shape'),
    sa.CheckConstraint('fuzzy_lower IS NULL OR (fuzzy_lower <= fuzzy_middle AND fuzzy_middle <= fuzzy_upper)', name='ck_validation_normalized_answers_fuzzy_order'),
    sa.CheckConstraint('length(trim(normalizer_version)) > 0', name='ck_validation_normalized_answers_version_nonempty'),
    sa.ForeignKeyConstraint(['submission_answer_id'], ['submission_answers.submission_answer_id'], name='fk_validation_normalized_answers_answer_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['validation_id'], ['submission_validations.validation_id'], name='fk_validation_normalized_answers_validation_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('validation_id', 'submission_answer_id', name=op.f('pk_validation_normalized_answers'))
    )
    with op.batch_alter_table('validation_normalized_answers', schema=None) as batch_op:
        batch_op.create_index('ix_validation_normalized_answers_answer_id', ['submission_answer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validation_normalized_answers', schema=None) as batch_op:
        batch_op.drop_index('ix_validation_normalized_answers_answer_id')

    op.drop_table('validation_normalized_answers')
    with op.batch_alter_table('validation_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_validation_messages_validation_severity')
        batch_op.drop_index('ix_validation_messages_question_id')

    op.drop_table('validation_messages')
    with op.batch_alter_table('participant_criterion_weights', schema=None) as batch_op:
        batch_op.drop_index('ix_participant_criterion_weights_criterion_id')

    op.drop_table('participant_criterion_weights')
    with op.batch_alter_table('submission_validations', schema=None) as batch_op:
        batch_op.drop_index('ix_submission_validations_submission_status')
        batch_op.drop_index('ix_submission_validations_input_hash')
        batch_op.drop_index('ix_submission_validations_implementation_id')
        batch_op.drop_index('ix_submission_validations_completed_at')

    op.drop_table('submission_validations')
    # ### end Alembic commands ###
