"""Manual reporting, supporting documents, editorial review, and releases.

Revision ID: 0014
Revises: 0013
"""

import sqlalchemy as sa
from alembic import op

from poli_insight.infrastructure.database.types import UTCDateTime, UUIDString

revision = "0014"
down_revision = "0013"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "supporting_documents",
        sa.Column("document_id", UUIDString(), nullable=False),
        sa.Column("session_id", UUIDString(), nullable=False),
        sa.Column("head_number", sa.Integer(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.CheckConstraint("head_number >= 1", name="ck_supporting_document_head"),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.session_id"],
            name=op.f("fk_supporting_documents_session_id_sessions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("document_id", name=op.f("pk_supporting_documents")),
    )
    op.create_index(
        op.f("ix_supporting_documents_session_id"),
        "supporting_documents",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "supporting_document_versions",
        sa.Column("version_id", UUIDString(), nullable=False),
        sa.Column("document_id", UUIDString(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("source_reference", sa.Text(), nullable=False),
        sa.Column("classification", sa.String(length=20), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("media_type", sa.String(length=100), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.CheckConstraint(
            "classification IN ('shareable', 'confidential')",
            name="ck_supporting_document_class",
        ),
        sa.CheckConstraint("number >= 1", name="ck_supporting_document_version"),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["supporting_documents.document_id"],
            name=op.f(
                "fk_supporting_document_versions_document_id_supporting_documents"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "version_id", name=op.f("pk_supporting_document_versions")
        ),
        sa.UniqueConstraint(
            "document_id", "number", name="uq_supporting_document_version"
        ),
    )
    op.create_table(
        "supporting_document_approvals",
        sa.Column("approval_id", UUIDString(), nullable=False),
        sa.Column("version_id", UUIDString(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["supporting_document_versions.version_id"],
            name=op.f(
                "fk_supporting_document_approvals_version_id_supporting_document_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "approval_id", name=op.f("pk_supporting_document_approvals")
        ),
        sa.UniqueConstraint(
            "version_id", name=op.f("uq_supporting_document_approvals_version_id")
        ),
    )
    op.create_table(
        "manual_reports",
        sa.Column("report_id", UUIDString(), nullable=False),
        sa.Column("session_id", UUIDString(), nullable=False),
        sa.Column("package_run_id", UUIDString(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("head_number", sa.Integer(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.CheckConstraint("head_number >= 1", name="ck_manual_report_head"),
        sa.ForeignKeyConstraint(
            ["package_run_id"],
            ["result_package_runs.package_run_id"],
            name=op.f("fk_manual_reports_package_run_id_result_package_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.session_id"],
            name=op.f("fk_manual_reports_session_id_sessions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("report_id", name=op.f("pk_manual_reports")),
    )
    op.create_index(
        op.f("ix_manual_reports_session_id"),
        "manual_reports",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "report_moderator_notes",
        sa.Column("note_id", UUIDString(), nullable=False),
        sa.Column("report_id", UUIDString(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["manual_reports.report_id"],
            name=op.f("fk_report_moderator_notes_report_id_manual_reports"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("note_id", name=op.f("pk_report_moderator_notes")),
    )
    op.create_index(
        op.f("ix_report_moderator_notes_report_id"),
        "report_moderator_notes",
        ["report_id"],
        unique=False,
    )
    op.create_table(
        "report_revisions",
        sa.Column("revision_id", UUIDString(), nullable=False),
        sa.Column("report_id", UUIDString(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("parent_revision_id", UUIDString(), nullable=True),
        sa.Column("sections", sa.JSON(), nullable=False),
        sa.Column("evidence_refs", sa.JSON(), nullable=False),
        sa.Column("document_ids", sa.JSON(), nullable=False),
        sa.Column("change_summary", sa.Text(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.CheckConstraint("number >= 1", name="ck_report_revision_number"),
        sa.ForeignKeyConstraint(
            ["parent_revision_id"],
            ["report_revisions.revision_id"],
            name=op.f("fk_report_revisions_parent_revision_id_report_revisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["manual_reports.report_id"],
            name=op.f("fk_report_revisions_report_id_manual_reports"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("revision_id", name=op.f("pk_report_revisions")),
        sa.UniqueConstraint("report_id", "number", name="uq_report_revision_number"),
    )
    op.create_table(
        "report_review_decisions",
        sa.Column("decision_id", UUIDString(), nullable=False),
        sa.Column("revision_id", UUIDString(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("warnings_acknowledged", sa.Boolean(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.CheckConstraint(
            "status IN ('submitted', 'approved', 'rejected')",
            name="ck_report_review_status",
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["report_revisions.revision_id"],
            name=op.f("fk_report_review_decisions_revision_id_report_revisions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("decision_id", name=op.f("pk_report_review_decisions")),
        sa.UniqueConstraint("revision_id", "number", name="uq_report_review_number"),
    )
    op.create_table(
        "report_releases",
        sa.Column("release_id", UUIDString(), nullable=False),
        sa.Column("session_id", UUIDString(), nullable=False),
        sa.Column("revision_id", UUIDString(), nullable=False),
        sa.Column("approval_id", UUIDString(), nullable=False),
        sa.Column("audience", sa.String(length=20), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("withdrawn_at", UTCDateTime(), nullable=True),
        sa.Column("withdrawn_by", sa.String(length=100), nullable=True),
        sa.Column("withdrawal_reason", sa.Text(), nullable=True),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.CheckConstraint(
            "(status = 'active' AND withdrawn_at IS NULL AND withdrawn_by IS NULL AND withdrawal_reason IS NULL) OR (status = 'withdrawn' AND withdrawn_at IS NOT NULL AND withdrawn_by IS NOT NULL AND withdrawal_reason IS NOT NULL)",
            name="ck_report_release_withdrawal",
        ),
        sa.CheckConstraint(
            "audience IN ('participant', 'public')", name="ck_report_release_audience"
        ),
        sa.CheckConstraint(
            "status IN ('active', 'withdrawn')", name="ck_report_release_status"
        ),
        sa.CheckConstraint("number >= 1", name="ck_report_release_number"),
        sa.ForeignKeyConstraint(
            ["approval_id"],
            ["report_review_decisions.decision_id"],
            name=op.f("fk_report_releases_approval_id_report_review_decisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["report_revisions.revision_id"],
            name=op.f("fk_report_releases_revision_id_report_revisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.session_id"],
            name=op.f("fk_report_releases_session_id_sessions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("release_id", name=op.f("pk_report_releases")),
        sa.UniqueConstraint(
            "session_id", "audience", "number", name="uq_report_release_number"
        ),
    )
    op.create_index(
        "uq_report_release_active",
        "report_releases",
        ["session_id", "audience"],
        unique=True,
        sqlite_where=sa.text("status = 'active'"),
        postgresql_where=sa.text("status = 'active'"),
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table("report_releases")
    op.drop_table("report_review_decisions")
    op.drop_table("report_revisions")
    op.drop_table("report_moderator_notes")
    op.drop_table("manual_reports")
    op.drop_table("supporting_document_approvals")
    op.drop_table("supporting_document_versions")
    op.drop_table("supporting_documents")
