"""baseline schema

Revision ID: 37e9bcfd4f50
Revises: 
Create Date: 2026-07-15 22:38:59.609381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37e9bcfd4f50'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenario_snapshots',
    sa.Column('scenario_id', sa.String(length=100), nullable=False),
    sa.Column('scenario_version', sa.String(length=50), nullable=False),
    sa.Column('scenario_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('config_snapshot_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('scenario_id', 'scenario_version', name=op.f('pk_scenario_snapshots'))
    )
    op.create_table('session_stakeholder_groups',
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('stakeholder_group_id', sa.String(length=100), nullable=False),
    sa.Column('stakeholder_group_name', sa.String(length=255), nullable=False),
    sa.Column('default_voting_power', sa.Float(), nullable=False),
    sa.Column('current_voting_power', sa.Float(), nullable=False),
    sa.Column('normalized_voting_power', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('session_id', 'stakeholder_group_id', name=op.f('pk_session_stakeholder_groups'))
    )
    op.create_table('sessions',
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('scenario_id', sa.String(length=100), nullable=False),
    sa.Column('scenario_version', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.Column('participation_method', sa.String(length=50), nullable=False),
    sa.Column('preference_scale', sa.String(length=50), nullable=False),
    sa.Column('weighting_method', sa.String(length=50), nullable=False),
    sa.Column('ranking_method', sa.String(length=50), nullable=False),
    sa.Column('aggregation_method', sa.String(length=50), nullable=False),
    sa.Column('require_access_code', sa.Boolean(), nullable=False),
    sa.Column('access_code_type', sa.String(length=50), nullable=True),
    sa.Column('allow_resubmissions', sa.Boolean(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_sessions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('session_stakeholder_groups')
    op.drop_table('scenario_snapshots')
    # ### end Alembic commands ###
