"""add session relationships

Revision ID: 768943a832ab
Revises: 37e9bcfd4f50
Create Date: 2026-07-15 22:54:46.040876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '768943a832ab'
down_revision: Union[str, Sequence[str], None] = '37e9bcfd4f50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_stakeholder_groups', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_session_stakeholder_groups_session', 'sessions', ['session_id'], ['session_id'], ondelete='CASCADE')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_sessions_scenario_snapshot', 'scenario_snapshots', ['scenario_id', 'scenario_version'], ['scenario_id', 'scenario_version'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sessions_scenario_snapshot', type_='foreignkey')

    with op.batch_alter_table('session_stakeholder_groups', schema=None) as batch_op:
        batch_op.drop_constraint('fk_session_stakeholder_groups_session', type_='foreignkey')

    # ### end Alembic commands ###
