"""add submission validation

Revision ID: c53421efa8ea
Revises: fadc0f540dba
Create Date: 2026-07-25 03:17:39.016349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c53421efa8ea'
down_revision: Union[str, Sequence[str], None] = 'fadc0f540dba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission_validations',
    sa.Column('validation_id', sa.String(length=100), nullable=False),
    sa.Column('submission_id', sa.String(length=100), nullable=False),
    sa.Column('answers_hash', sa.String(length=64), nullable=False),
    sa.Column('weighting_method', sa.String(length=50), nullable=False),
    sa.Column('validator_version', sa.String(length=100), nullable=False),
    sa.Column('completion_ratio', sa.Float(), nullable=False),
    sa.Column('weights_json', sa.Text(), nullable=False),
    sa.Column('consistency_ratio', sa.Float(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('errors_json', sa.Text(), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('validated_by', sa.String(length=100), nullable=False),
    sa.CheckConstraint('completion_ratio >= 0.0 AND completion_ratio <= 1.0', name='ck_submission_validations_completion_ratio'),
    sa.CheckConstraint('consistency_ratio IS NULL OR consistency_ratio >= 0.0', name='ck_submission_validations_consistency_ratio'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submission_id'], name='fk_submission_validation_submissions', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('validation_id', name=op.f('pk_submission_validations')),
    sa.UniqueConstraint('submission_id', 'answers_hash', 'weighting_method', 'validator_version', name='uq_submission_validations_input_version')
    )
    with op.batch_alter_table('submission_validations', schema=None) as batch_op:
        batch_op.create_index('ix_submission_validations_submission', ['submission_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_validations', schema=None) as batch_op:
        batch_op.drop_index('ix_submission_validations_submission')

    op.drop_table('submission_validations')
    # ### end Alembic commands ###
