"""add participants and submissions

Revision ID: fadc0f540dba
Revises: 768943a832ab
Create Date: 2026-07-22 01:54:22.998925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fadc0f540dba'
down_revision: Union[str, Sequence[str], None] = '768943a832ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('participant_id', sa.String(length=100), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('stakeholder_group_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('alias', sa.String(length=100), nullable=True),
    sa.Column('access_status', sa.String(length=50), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disabled_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False),
    sa.CheckConstraint("access_status <> 'disabled' OR (disabled_at IS NOT NULL AND disabled_by IS NOT NULL)", name='ck_session_participants_disabled_metadata'),
    sa.CheckConstraint("access_status IN ('active', 'disabled', 'withdrawn')", name='ck_participants_access_status'),
    sa.CheckConstraint('updated_at >= created_at', name='ck_session_participants_update_time'),
    sa.ForeignKeyConstraint(['session_id', 'stakeholder_group_id'], ['session_stakeholder_groups.session_id', 'session_stakeholder_groups.stakeholder_group_id'], name='fk_participants_session_stakeholder_group', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], name='fk_session_participants_session', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('participant_id', name=op.f('pk_participants')),
    sa.UniqueConstraint('session_id', 'alias', name='uq_session_participants_session_alias'),
    sa.UniqueConstraint('session_id', 'user_id', name='uq_session_participants_session_user')
    )
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participants_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_session_participants_session_group', ['session_id', 'stakeholder_group_id'], unique=False)
        batch_op.create_index('ix_session_participants_session_status', ['session_id', 'access_status'], unique=False)

    op.create_table('submissions',
    sa.Column('submission_id', sa.String(length=100), nullable=False),
    sa.Column('participant_id', sa.String(length=100), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('previous_submission_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('answers_json', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_saved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_by', sa.String(length=100), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawn_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False),
    sa.CheckConstraint("status <> 'draft' OR submitted_at IS NULL", name='ck_submissions_draft_not_submitted'),
    sa.CheckConstraint("status <> 'superseded' OR superseded_at IS NOT NULL", name='ck_submissions_superseded_time'),
    sa.CheckConstraint("status <> 'withdrawn' OR withdrawn_at IS NOT NULL", name='ck_submissions_withdrawn_time'),
    sa.CheckConstraint("status IN ('draft', 'submitted', 'superseded', 'withdrawn')", name='ck_submissions_status'),
    sa.CheckConstraint("status NOT IN ('submitted', 'superseded') OR (submitted_at IS NOT NULL AND submitted_by IS NOT NULL)", name='ck_submissions_submitted_metadata'),
    sa.CheckConstraint('attempt_number >= 1', name='ck_submissions_attempt_number'),
    sa.CheckConstraint('submitted_at IS NULL OR submitted_at >= started_at', name='ck_submissions_submission_time'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.participant_id'], name='fk_submissions_participant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['previous_submission_id'], ['submissions.submission_id'], name='fk_submissions_previous_submission', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('submission_id', name=op.f('pk_submissions')),
    sa.UniqueConstraint('participant_id', 'attempt_number', name='uq_submissions_participant_attempt')
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index('ix_submissions_participant_status', ['participant_id', 'status'], unique=False)
        batch_op.create_index('uq_submissions_one_draft_per_participant', ['participant_id'], unique=True, postgresql_where=sa.text("status = 'draft'"), sqlite_where=sa.text("status = 'draft'"))
        batch_op.create_index('uq_submissions_one_effective_per_participant', ['participant_id'], unique=True, postgresql_where=sa.text("status = 'submitted'"), sqlite_where=sa.text("status = 'submitted'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index('uq_submissions_one_effective_per_participant', postgresql_where=sa.text("status = 'submitted'"), sqlite_where=sa.text("status = 'submitted'"))
        batch_op.drop_index('uq_submissions_one_draft_per_participant', postgresql_where=sa.text("status = 'draft'"), sqlite_where=sa.text("status = 'draft'"))
        batch_op.drop_index('ix_submissions_participant_status')

    op.drop_table('submissions')
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_index('ix_session_participants_session_status')
        batch_op.drop_index('ix_session_participants_session_group')
        batch_op.drop_index(batch_op.f('ix_participants_user_id'))

    op.drop_table('participants')
    # ### end Alembic commands ###
