"""Persistence port for immutable analysis runs."""

from __future__ import annotations

from typing import Protocol

from poli_insight.domain.analysis import AnalysisRun, AnalysisRunSummary


class AnalysisRunRepository(Protocol):
    def add(self, run: AnalysisRun) -> None: ...
    def get(self, analysis_run_id: str) -> AnalysisRun | None: ...
    def list_for_session(self, session_id: str) -> tuple[AnalysisRun, ...]: ...
    def list_summaries_for_session(
        self, session_id: str
    ) -> tuple[AnalysisRunSummary, ...]: ...
    def list_for_ranking(self, ranking_run_id: str) -> tuple[AnalysisRun, ...]: ...
    def find_success_by_input_hash(self, input_hash: str) -> AnalysisRun | None: ...
    def next_run_number(self, processing_run_id: str) -> int: ...
