"""Persistence port for validation bundle processing runs."""

from __future__ import annotations

from typing import Protocol

from poli_insight.domain.processing import ProcessingRun


class ProcessingRunRepository(Protocol):
    def add(self, run: ProcessingRun) -> None: ...
    def get(self, processing_run_id: str) -> ProcessingRun | None: ...
    def get_for_update(self, processing_run_id: str) -> ProcessingRun | None: ...
    def save(self, run: ProcessingRun) -> None: ...
    def next_run_number(self, session_id: str) -> int: ...
    def list_for_session(self, session_id: str) -> tuple[ProcessingRun, ...]: ...

