"""Persistence port for immutable ranking runs."""

from __future__ import annotations

from typing import Protocol

from poli_insight.domain.ranking import RankingRun


class RankingRunRepository(Protocol):
    def add(self, run: RankingRun) -> None: ...
    def get(self, ranking_run_id: str) -> RankingRun | None: ...
    def list_for_session(self, session_id: str) -> tuple[RankingRun, ...]: ...
    def list_for_source(self, processing_run_id: str) -> tuple[RankingRun, ...]: ...
    def find_success_by_input_hash(self, input_hash: str) -> RankingRun | None: ...
    def next_run_number(self, session_id: str) -> int: ...
